# AI model config.

defaults:
  profile: qwen

profiles:
  qwen:
    api_key: sk-dfac621ea7044aa4886a9135cc0774ba
    provider: qwen
    region: cn-beijing

brains:
  text:
    model: qwen3.6-plus

  vision:
    model: qwen-vl-plus

  voice:
    model: cosyvoice-v3-flash

  image:
    model: qwen-image-2.0-pro
